### ISSUE TITLE
절대경로 -> 상대경로 수정 바람.

### ISSUE THREAD

**Issue by tjcky** [jsh4885/exp#10]
https://github.com/jsh4885/exp/blob/23e13a364792e58e1c96a4fc6368948e974c1f86/test05.py#L6

절대경로(C:// ..... //파일명) 을 사용하지 말고 상대경로로 수정바람. 현재 test5,py 파일과 동일한 디렉토리 내에 있는 파일을 불러오도록 해야함.

이유
- 해당 소스를 내가 pull 당겨 받으면, 나는 C 드라이브 내에 jsh 라는 폴더가 없음. 즉 협업을 하는 동료를 위해 절대경로가 아닌 상대경로를 써야 함. (또한, 나중에 서버단 작업의 경우를 위해서라도 상대경로가 맞음)

**Comment by tjcky** [comment]
어렵다 싶으면 코멘트 남겨줘요.

**Comment by jsh4885** [comment]
GUI만 보다가 수정 못했습니다...
저녁 중으로 수정하겠습니다!!
