### ISSUE TITLE
레파지토리 꾸미기

### ISSUE THREAD

**Issue by tjcky** [jsh4885/exp#12]
**배경**
- 현재 이 레파지토리는 여러 테스트용 소스가 많음 (계산기 소스, 기타 등등)
- 때문에, 소스를 분리해야함.

**내용**
1. 신규 레파지토리 생성하고, 
2. 네이밍도 알맞은 것을 정할것 (한글병합을 알아볼 수 있는)
3. Read.me 파일에도 이 레파지토리가 어떤것을 만드는 소스인지 배경, 기능, 이미지 등 상세한 설명을 써둘것.
4. 한글 병합과 관련된 소스만 옮겨둘 것. (이 레파지토리는 연습용 소스만 올리는 용도로 활용 예정)

**Comment by jsh4885** [comment]
https://github.com/jsh4885/HwpMerge.git
