### ISSUE TITLE
참고링크

### ISSUE THREAD

**Issue by tjcky** [jsh4885/exp#4]
참고링크
https://www.hancom.com/board/devmanualList.do?gnb0=25&gnb1=81

실제 실행파일을 commit 해두기

_Originally posted by @tjcky in https://github.com/jsh4885/exp/issues/3_

로컬(개인pc)에서 브랜치 병합하고 원격레파지토리로 push.
(소스코드가 이 프로젝트에서 보이지 않음)

**Comment by jsh4885** [comment]
실행 파일의 의미가 .exe파일 등을 지칭하시는 건가요?

**Comment by tjcky** [comment]
> 

아 소스코드(소스명.py)를 말하는거였어요.

**Comment by jsh4885** [comment]
올렸습니다!

**Comment by jsh4885** [comment]
다시 올렸습니다!
