### ISSUE TITLE
소스파일과 입력대상 한글파일간의 경로 확인

### ISSUE THREAD

**Issue by tjcky** [jsh4885/exp#5]
https://github.com/jsh4885/exp/blob/bfc3395fd63608ec82c146177655db99e76b0f0f/test01.py#L2

해당 테스트용 한글 파일(test01.hwp) 은 소스파일(test01.py) 과 동일한 경로(or 폴더)에 놓여있어야 하는지?

**Comment by jsh4885** [comment]
맞습니다
