### ISSUE TITLE
소스코드에서 한글 파일(.hwp) 을 읽어서 문장의 메타정보 추출해보기

### ISSUE THREAD

**Issue by tjcky** [jsh4885/exp#6]
소스 예시

1. 한글 파일(.hwp) 을 읽음
2. 한글 파일 내 문장, 예시로 " 우리는 대한민국 사람입니다 " 라는 문장이 있다면,
3. print "글자크기 : ", fontsize , "문장길이 : " lenText ....

**Comment by jsh4885** [comment]
hwp 텍스트 추출 후 문장길이 까지 추출했습니다!

**Comment by tjcky** [comment]
코드봤어요.
주중에 실행해보고 확인해볼께요
