### ISSUE TITLE
gui 이해

### ISSUE THREAD

**Issue by tjcky** [jsh4885/exp#7]
main.py 가 계산기 GUI (그래픽 유저 인터페이스) 프로그램임.

1. 소스 분석 해보고
2. 동작 원리 파악 해두기

**Comment by jsh4885** [comment]
현재 진행중인 내용을 test03으로 올렸습니다
추후 완료하겠습니다!

**Comment by jsh4885** [comment]
분석과 동작 원리 파악 완료 했습니다!
