### ISSUE TITLE
한글파일병합.exe 기획서 (안)

### ISSUE THREAD

**Issue by tjcky** [jsh4885/exp#9]
[한글파일병합 기획서.pptx](https://github.com/jsh4885/exp/files/10674575/default.pptx)

**Comment by tjcky** [comment]
기획안 이해 안되면 말씀주세요.

**Comment by tjcky** [comment]
[한글파일병합 기획서_230212.pptx](https://github.com/jsh4885/exp/files/10715156/_230212.pptx)

좀더 상세한 설명 넣었어요.
요구사항 생각나는대로 파일명에 뒤에 날짜만 바꾸고 계속 업로드 할께요.

**Comment by jsh4885** [comment]
실행 파일과 병합하려는 파일들이 같은 폴더에 있어야 한다는 미흡한 부분이 있지만
완성했습니다!

**Comment by tjcky** [comment]
확인했어요.
이 부분은 제가 수정해볼꼐요.
